palette:
  brand-primary: '#3268bf'
  brand-secondary: '#4d90fe'
  brand-accent: '#ffc107'
  brand-link: '#a7d9f5'
  navbar-bg: '#00326d'
  navbar-text: '#ffffff'
  navbar-active-bg: '#0d0d0d'
  navbar-active-text: '#fffbf7'
  navbar-sec-bg: '#0D4C96'
  navbar-sec-text: '#f7f7ff'
logo: 'public://color/t4ddiaspora-f2ca2e84/logo.svg'
stylesheets:
  - 'public://color/t4ddiaspora-f2ca2e84/brand.css'
files:
  - 'public://color/t4ddiaspora-f2ca2e84/logo.svg'
  - 'public://color/t4ddiaspora-f2ca2e84/brand.css'
