palette:
  brand-primary: '#F75940'
  brand-secondary: '#334252'
  brand-accent: '#3DC7BE'
  brand-link: '#f4806d'
  navbar-bg: '#263342'
  navbar-text: '#ffffff'
  navbar-active-bg: '#fc715c'
  navbar-active-text: '#fffbf7'
  navbar-sec-bg: '#2d3945'
  navbar-sec-text: '#f7f7ff'
logo: 'public://color/t4ddiaspora-c50e6411/logo.svg'
stylesheets:
  - 'public://color/t4ddiaspora-c50e6411/brand.css'
files:
  - 'public://color/t4ddiaspora-c50e6411/logo.svg'
  - 'public://color/t4ddiaspora-c50e6411/brand.css'
