theme: default
defaults:
  sender: social_swiftmailer
  formatter: social_swiftmailer
_core:
  default_config_hash: IhwTepsVwtbtbcT5GzQKhCXDCRvbk3MNkWqPiuiZ10s
modules:
  swiftmailer:
    none:
      formatter: social_swiftmailer
      sender: social_swiftmailer
  activity_send_email:
    All:
      formatter: social_swiftmailer
      sender: social_swiftmailer
  user:
    All:
      formatter: SMTPMailSystem
      sender: SMTPMailSystem
  private_message:
    All:
      formatter: social_swiftmailer
      sender: social_swiftmailer
