theme: default
defaults:
  sender: SMTPMailSystem
  formatter: SMTPMailSystem
_core:
  default_config_hash: IhwTepsVwtbtbcT5GzQKhCXDCRvbk3MNkWqPiuiZ10s
modules:
  swiftmailer:
    none:
      formatter: social_swiftmailer
      sender: social_swiftmailer
  activity_send_email:
    All:
      formatter: social_swiftmailer
      sender: social_swiftmailer
  user:
    All:
      formatter: social_swiftmailer
      sender: social_swiftmailer
  private_message:
    All:
      formatter: social_swiftmailer
      sender: social_swiftmailer
  system:
    none:
      formatter: social_swiftmailer
      sender: social_swiftmailer
